#!/usr/bin/env sh

# Semantic versioning details: https://semver.org/
# Constants
RELEASE_PATCH="release-patch"
RELEASE_MINOR="release-minor"
RELEASE_MAJOR="release-major"
GET_GIT_VERSION="get-git-version"

DESCRIBE=$(git describe --always --tags)

VARSION=$(echo ${DESCRIBE} | grep -Eo ""^[0-9]\.[0-9]\.[0-9]"")

MAJOR=$(echo ${VARSION} | grep -Eo ""^[0-9]+"")
MINOR=$(echo ${VARSION} | grep -Eo "[0-9]+\.[0-9]+$" | grep -Eo "^[0-9]+")
PATCH=$(echo ${VARSION} | grep -Eo "[0-9]+$")

# Command line arguments.
if [ ${#} -lt 1 ];
then
  echo "Usage: ${0} [ ${RELEASE_PATCH} | ${RELEASE_MINOR} | ${RELEASE_MAJOR} ]"
  exit 1
fi

git pull

version_patch=$PATCH
version_minor=$MINOR
version_major=$MAJOR

echo "Current version: ${version_major}.${version_minor}.${version_patch}"

if [ ${1} = ${GET_GIT_VERSION} ];
then
  exit 0
elif [ ${1} = ${RELEASE_PATCH} ];
then
  let "version_patch=version_patch+1"
elif [ ${1} = ${RELEASE_MINOR} ];
then
  version_patch=0
  let "version_minor=version_minor+1"
elif [ ${1} = ${RELEASE_MAJOR} ];
then
  version_patch=0
  version_minor=0
  let "version_major=version_major+1"
fi

if [ -z "$(git status --porcelain)" ]; then 
  echo "Git repository is clean"
else 
  echo "Git repository not clean. Commit your changes"
  exit 1
fi

printf "New version: "
echo "${version_major}.${version_minor}.${version_patch}"

# Push the version tags to git
git tag -a "${version_major}.${version_minor}.${version_patch}" -m "${version_major}.${version_minor}.${version_patch}"
git push origin "${version_major}.${version_minor}.${version_patch}"